<br>
<?php foreach($this->view->elements as $key => $element) {?>
    <?php if(isset($_GET['id']) && $_GET['id'] === $element['id']) {?>

        <?php
        
            $name_file = explode('.', $element['name_file']);
            
        ?>

    <div class="m-5 box-newuser">
        
        <div class="bg-dark text-white p-2" style="border-top-left-radius: 17px;border-top-right-radius: 17px;">
            <h5 class="text-center">Editar <?= strtolower($element['title_element'])?> do slider de propagandas</h5>
        </div>
        <form action="/updateslider?acao=edit&id=<?= $_GET['id']?>" method="POST" enctype="multipart/form-data" class="row p-3">
            
            <div class="col-md-6">
                <div class="form-group">
                    <input id="nome" class="form-control" type="text" maxlength="25" name="nome" value="<?= $element['title_element']?>" placeholder="Nome e do elemento">
                </div>
                <hr>
                <div class="form-group">
                    <input id="url" class="form-control" type="url" name="url" value="<?= $element['link_element']?>" placeholder="http://www.exemple.com/"> 
                </div>
                <hr>
                <div class="form-group">
                    <input id="name_file" class="form-control" type="text" name="new_name" value="<?= $name_file[0] ?>" placeholder="Nome da imagem" readonly>              
                </div>
                <hr>
                <div class="input-group">
                    <input id="fileUpload" type="file" name="imagem">
                </div>
                <hr>
                <div class="form-group shadow-textarea">
                    <textarea class="form-control" rows="3" name="descricao" maxlength="90" value="<?= $element['desc_element']?>" placeholder="Descreva uma tagline para anuncio..."></textarea>
                </div>
                
            </div>

            <div class="col-md-6">
                <div align="center" class="m-5 text-primary">
                    <i class="fas fa-newspaper fa-7x"></i><br>
                    <button class="btn-custom-cadastro">Editar</button>                    
                    <?php if(isset($_GET['acaoedit']) && $_GET['acaoedit'] == 'error') {?>
                        <div class="mt-3">
                            <span style="font-size: 1.3em;" class="text-danger">Informções inválidas ou um arquivo não foi selecionado!</span>
                        </div>
                    <?php } else if(isset($_GET['acaoedit']) && $_GET['acaoedit'] == 'success') {?>
                        <div class="mt-3" >
                            <span style="font-size: 1.3em;" class="text-success">Elemento editado com sucesso!</span>
                        </div>
                    <?php }?>

                    <div class="remove-element">
                        <span>
                            <a href="/removeslider?acao=remove&id=<?= $_GET['id']?>&filename=<?= $element['name_file']?>">Remover o elemento da lista</a>
                        </span>
                    </div>
                </div>
            </div>
        </form>

    </div>
    <?php } ?>
<?php } ?>
