<br>
<div>
    <?php if(isset($_GET['msg']) && $_GET['msg'] == 'success') {?>
        <div class="row box-mensagem">
            <div class="col-md-12">

                <div class="card-body font-weight-bold">
                    <table class="table table-bordered ">
                        <thead>
                            <tr>
                                <td colspan="3" class="bg-dark">
                                    <a href="/contato"><i style="cursor: pointer;" class="fas fa-arrow-left text-white"></i></a>
                                </td>

                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td scope="col" colspan="3">
                                    <div class="row">
                                        <div class="col-11 border m-auto text-center">
                                            <h3 class="text-success">Contato enviado com sucesso</h3>										
                                        </div>									
                                    </div>
                                </td>
                            </tr>				
                                                    
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div class="row box-mensagem">
            <div class="col-md-12">
                <?php foreach($this->view->dados as $key => $dado) {?>
                <?php if($dado['id'] == $_GET['id']) {?>
                <div class="card-body font-weight-bold">
            
                    <table class="table table-bordered ">
                        <thead>
                            <tr>
                                <td colspan="4" style="background: rgba(0, 0, 0, 0.274);" class="bg-dark">
                                    <a href="/contato"><i style="cursor: pointer;" class="fas fa-arrow-left text-white"></i></a>
                                    <?if(isset($_GET['form']) && $_GET['form'] == 'true'){?>
                                        <a href="/mensagem?id=<?= $dado['id']?>"><i style="cursor: pointer;" class="far fa-paper-plane fa-lg text-white float-right">&#xa0;close</i></a>
                                    <?} else {?>		
                                        <a href="/mensagem?id=<?= $dado['id']?>&form=true"><i style="cursor: pointer;" class="far fa-paper-plane fa-lg text-white float-right">&#xa0;open</i></a>
                                    <?}?>

                                </td>

                            </tr>
                        </thead>
                        <tbody style="font-size:1.3em">
                        
                            <tr>
                                <td scope="col" ><span><h6>Nome:</h6></span><?= utf8_encode($dado['name'])?></td>
                                <td scope="col" colspan="2" ><span><h6>Remetente:</h6></span><?= utf8_encode($dado['mail'])?></td>
                                <td scope="col" ><span><h6>Tipo:</h6></span><?= utf8_encode($dado['subject'])?></td>
                            </tr>		

                            <tr>                               
                                <td scope="col" ><span><h6>Pais:</h6></span><?= utf8_encode($dado['country'])?></td>							
                                <td scope="col" ><span><h6>Estado:</h6></span><?= utf8_encode($dado['estado'])?></td>							
                                <td scope="col" ><span><h6>Cidade:</h6></span><?= utf8_encode($dado['city'])?></td>		
                                <td scope="col" ><span><h6>Data e Hora:</h6></span><?= utf8_encode($dado['data_system'])?></td>					
                            </tr>

                            <tr>                                
                                <td scope="col" ><span><h6>Contato:</h6></span><?= utf8_encode($dado['tel'])?></td>							
                                <td scope="col" ><span><h6>Ip do remetente:</h6></span><?= utf8_encode($dado['ip'])?></td>							
                                <td scope="col" colspan="2" ><span><h6>Provedor:</h6></span><?= utf8_encode($dado['provedor'])?></td>						                               							
                            </tr>

                            <tr>
                                <td scope="col" colspan="3">
                                    <div class="box-m">
                                        <div class="border">
                                            <h6 class="text-left">Mensagem: </h6><br>
                                            <p><?= utf8_encode($dado['message'])?></p>
                                        </div>
                                    </div>
                                </td>
                            </tr>
        
                        </tbody>
                    </table>
                <?php } ?>
                <?php } ?>       

                <hr>
                
                <?php if(isset($_GET['form']) && $_GET['form'] == 'true') {?>
                <div class="card-body font-weight-bold">
                    <?php foreach($this->view->dados as $key => $dado) {?>
                    <?php if($dado['id'] == $_GET['id']) {?>
                    <form action="/sendmail" method="post">
                        <div class="form-group">
                            <label for="para">Para</label>
                            <input type="text" class="form-control" id="para" name="email" value="<?= utf8_encode($dado['mail'])?>" placeholder="joao@dominio.com.br">
                        </div>

                        <div class="form-group">
                            <label for="assunto">Assunto</label>
                            <input type="text" class="form-control" id="assunto" name="assunto" value="<?= utf8_encode($dado['subject'])?>" placeholder="Assundo do e-mail">
                        </div>

                        <div class="form-group">
                            <label for="mensagem">Mensagem</label>
                            <textarea class="form-control" id="mensagem" name="mensagem" placeholder="Responder..."></textarea>
                        </div>

                        <button type="submit" class="btn btn-custom-mail btn-lg">Enviar Mensagem</button>
                    </form>
                </div>
                    <?php } ?>
                    <?php } ?>
                <?php } ?>

                </div>
            </div>
        </div>

    <?php }?>
</div>
