<br>

<div class="m-5 box-newuser">
    
    <div class="bg-dark text-white p-2" style="border-top-left-radius: 17px;border-top-right-radius: 17px;">
        <h5 class="text-center">Cadastrar um novo elemento no slider de propagandas</h5>
    </div>
    <form action="/cadastrarslider" method="POST" enctype="multipart/form-data" class="row p-3">
        
        <div class="col-md-6">
            <div class="form-group">
                <input id="nome" class="form-control" type="text" maxlength="25" name="nome" placeholder="Nome e do elemento">
            </div>
            <hr>
            <div class="form-group">
                <input id="url" class="form-control" type="url" name="url" placeholder="http://www.exemple.com"> 
            </div>
            <hr>
            <div class="form-group">
                <input id="name_file" class="form-control" type="text" name="new_name" placeholder="Nome da imagem">              
            </div>
            <hr>
            <div class="input-group">
                <input id="fileUpload" type="file" name="imagem">
            </div>
            <hr>
            <div class="form-group shadow-textarea">
                <textarea max="100" class="form-control" maxlength="90" rows="3" name="descricao" placeholder="Descreva uma tagline para anuncio..."></textarea>
            </div>
            
        </div>

        <div class="col-md-6">
            <div align="center" class="m-5 text-primary">
                <i class="fas fa-newspaper fa-7x"></i><br>
                <button class="btn-custom-cadastro">Cadastrar</button>
                <?php if(isset($_GET['acao']) && $_GET['acao'] == 'error') {?>
                    <div class="mt-3">
                        <span style="font-size: 1.3em;" class="text-danger">Informções inválidas ou o arquivo não foi selecionado!</span>
                    </div>
                <?php } else if(isset($_GET['acao']) && $_GET['acao'] == 'success') {?>
                    <div class="mt-3" >
                        <span style="font-size: 1.3em;" class="text-success">Um novo elemento foi cadastrado com sucesso!</span>
                    </div>
                <?php }?>
            </div>
        </div>
    </form>

</div>