<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="./assets/css/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="./assets/css/elements.css">
    <link rel="stylesheet" type="text/css" href="./assets/css/maincss.css">


    <script>
      $(window).ready(() => {
        $('#refresh').click(() => {
          window.location.reload();
        })
      })
    </script>

    <title>MiniSystem</title>
  </head>
  <body class="background-lateral">

    <nav class="navbar navbar-dark bg-white flex-md-nowrap shadow inline-block" style="padding: 10px;">
      <a href="/dashboard" class="logo mr-0">MiniSystem</a>

      <div class="box-search">
        <button class="btn" type="button" name="button"><i class="fas fa-bars"> Menu</i></button>

        <input class="pl-3 form-search" type="text" name="pesquisa" placeholder="search">
      </div>
      <div class="" style="margin-right: 10px;">
        <ul class="navbar-topo">
          <li>
            <a href="#" class="text-dark"><i class="fas fa-cog"></i>&#xa0;Configurações</a>
          </li>
          
          <li class="">
            <a href="/sair" class="text-dark">Sair</a>
          </li>
        </ul>
      </div>

    </nav>

    <div class="coluna-left">
      <div style="">
          <ul>
            <li class="nav-item"><a href="/dashboard" id="contato"><i class="fa fa-tachometer-alt sidebar-icon"></i>&#xa0;&#xa0;Painel</a></li>
            <li class="nav-item"><a href="/contato" id="contato"><i class="far fa-id-card"></i>&#xa0;&#xa0;Contatos</a></li>
            <li class="nav-item"><a href="/usuarios" id="newuser"><i class="fas fa-users"></i>&#xa0;&#xa0;Usuários</a></li>
            <li class="nav-item"><a href="/newuser" id="newuser"><i class="fas fa-users-cog"></i>&#xa0;&#xa0;Novo Usuário</a></li>
          </ul>
      </div>
    </div>

    <div id="area-prinfipal">
      <div class="container-fluid container-custom mt-1">
        <div class="row">
          <div class="col-md-12"><!-- Inicio Conteudo-->
            <?= $this->content();?>
          </div><!-- Fim Conteudo-->
        </div>
      </div>
    </div>
    <br>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>