<? $log = isset($_SESSION['id_type']) ? $_SESSION['id_type'] : $log;?>
<!doctype html>
<html lang="en">
  <head>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sistema de gerenciamento de sites">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
		<meta name="author" content="Luan Santos">

		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

		
		<!-- Font Awesome CSS -->
		<link href="./assets/css/fontawesome/css/all.css" rel="stylesheet" type="text/css" />
		
		<!-- Custom CSS -->
        <link href="./assets/css/css2/style.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="./assets/css/elements.css">
        <link rel="stylesheet" type="text/css" href="./assets/css/maincss.css">
        <link rel="stylesheet" href="./assets/css/style.css">
        
		
		<!-- BEGIN CSS for this page -->
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css"/>
        <!-- END CSS for this page --> 

        <style>
            #Notfy-dados {
                overflow-y: auto; 
                height: 300px;
            }
            #Notfy-dados::-webkit-scrollbar {
                width: 3px;
                background: rgba(0, 0, 0, .3);
            }
            #Notfy-dados::-webkit-scrollbar-thumb {
                background: rgba(0, 0, 0, .2);
                border-radius: 10px;
            }
        </style>
        
        <script>
            $(window).ready(() => {
                $('#refresh').click(() => {
                window.location.reload();
                })
            })
        </script>
        <!--  -->
        <script src="./assets/js/js-panel/jquery-system.js"></script>

    <title>MiniSystem</title>
  </head>

  <body class="adminbody">
    
    <div id="main">
    
        <!-- top bar navigation -->
        <div class="headerbar">
    
            <!-- LOGO -->
            <div class="headerbar-left">
                <a href="/dashboard" class="logo">
                    <span>
                        <i class="navbar-brand font-weight-bold text-white fas fa-shield-alt"></i>MiniSystem
                    </span>
                </a>
            </div>
    
            <nav class="navbar-custom">
    
                        <ul class="list-inline float-right mb-0">
                            
                            <li class="list-inline-item dropdown notif">
                                <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <i class="fa fa-fw fa-question-circle"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-arrow-success dropdown-lg">
                                    <!-- item-->
                                    <div class="dropdown-item noti-title">
                                        <h5><small>Help and Support</small></h5>
                                    </div>
    
                                    <!-- item-->
                                    <a target="_blank" href="#" class="dropdown-item notify-item">                                    
                                        <p class="notify-details ml-0">
                                            <b>Do you want custom development to integrate this theme?</b>
                                            <span>Contact Us</span>
                                        </p>
                                    </a>
    
                                    <!-- item-->
                                    <a target="_blank" href="#" class="dropdown-item notify-item">                                    
                                        <p class="notify-details ml-0">
                                            <b>Do you want PHP version of the theme that save dozens of hours of work?</b>
                                            <span>Try Pike Admin PRO</span>
                                        </p>
                                    </a>                               
    
                                    <!-- All-->
                                    <a title="Clcik to visit Pike Admin Website" target="_blank" href="#" class="dropdown-item notify-item notify-all">
                                        <i class="fa fa-link"></i> Visit Pike Admin Website
                                    </a>
    
                                </div>
                            </li>
                            
                            <li class="list-inline-item dropdown notif">
                                <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <i class="fa fa-fw fa-question-circle"></i><span class="notif-bullet"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-arrow-success dropdown-lg">
                                    <!-- item-->
                                    <div class="dropdown-item noti-title">
                                        <h5><small><span class="label label-danger pull-xs-right"></span>Contact Messages</small></h5>
                                    </div>
    
                                    <!-- item-->
                                    <a href="#" class="dropdown-item notify-item">                                    
                                        <p class="notify-details ml-0">
                                            <b>Jokn Doe</b>
                                            <span>New message received</span>
                                            <small class="text-muted">2 minutes ago</small>
                                        </p>
                                    </a>
    
                                    <!-- item-->
                                    <a href="#" class="dropdown-item notify-item">                                    
                                        <p class="notify-details ml-0">
                                            <b>Michael Jackson</b>
                                            <span>New message received</span>
                                            <small class="text-muted">15 minutes ago</small>
                                        </p>
                                    </a>
    
                                    <!-- item-->
                                    <a href="#" class="dropdown-item notify-item">                                    
                                        <p class="notify-details ml-0">
                                            <b>Foxy Johnes</b>
                                            <span>New message received</span>
                                            <small class="text-muted">Yesterday, 13:30</small>
                                        </p>
                                    </a>
    
                                    <!-- All-->
                                    <a href="#" class="dropdown-item notify-item notify-all">
                                        View All
                                    </a>
    
                                </div>
                            </li>
                            
                            <? if($log == "1" or $log == "3") {?>
                                <!-- abertura da tag li de notificações de e-mail. -->
                                <li class="list-inline-item dropdown notif">
                                    <a id="notif-bullet" class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                        <!--  -->
                                        <i class='fas fa-envelope-square'></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-lg">
                                        <!-- item-->
                                        <div class="dropdown-item noti-title">
                                            <h5><small><span id="Allerts" class="label label-danger pull-xs-right">                                            
                                            </span>Allerts</small></h5>
                                        </div>

                                        <div id="Notfy-dados">
                                            <!-- item-->
                                            <a id="link-notfy" href="/alterStatus?acao=alter&id=<?=$value['id']?>" class="dropdown-item notify-item">
                                                <p class="notify-details">
                                                    <b id="name-notfy"></b>
                                                    <span id="subject-notfy"></span>
                                                    <small id="data-system-notfy" class="text-muted"></small>
                                                </p>
                                            </a>
                                        </div>
        
                                        <!-- All-->
                                        <a href="/contato" class="dropdown-item notify-item notify-all"><b>Visualizar todos<i class="fas fa-plus float-right"></i></b>
                                        </a>
        
                                    </div>
                                </li> <!-- End  -->
                            <? } ?>
    
                            <li class="list-inline-item dropdown notif">
                                <a class="nav-link dropdown-toggle nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <img src="./assets/img/avatar2.png" alt="Profile image" class="avatar-rounded">
                                </a>
                                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                                    <!-- item-->
                                    <div class="dropdown-item noti-title">
                                        <h5 class="text-overflow text-center"><small>Olá <?= $_SESSION['user']?></small> </h5>
                                    </div>
    
                                    <!-- item-->
                                    <a href="/profile" class="dropdown-item notify-item text-center">
                                        <i class="fas fa-user"></i></i> <span>Profile</span>
                                    </a>
    
                                    <!-- item-->
                                    <a href="/sair" class="dropdown-item notify-item text-center">
                                        <i class="fa fa-power-off"></i> <span>Logout</span>
                                    </a>

                                </div>
                            </li>
    
                        </ul>
    
                        <ul class="list-inline menu-left mb-0">
                            <li class="float-left">
                                <button id="left-menu" class="button-menu-mobile open-left">
                                    <i class="fas fa-bars"></i>                                 

                                </button>
                            </li>                        
                        </ul>
    
            </nav>
    
        </div>
        <!-- End Navigation -->
        
     
        <!-- Left Sidebar -->
        <div class="left main-sidebar">
        
            <div class="sidebar-inner leftscroll">
    
                <div id="sidebar-menu">
            
                <ul>
    

                        <li class="submenu">
                            <a  href="/dashboard"><i class="fa fa-fw fa-tachometer-alt"></i><span> Dashboard </span> </a>
                        </li>


                        <? if($log == "1" or $log == "3") {?>
                            <li class="submenu">
                                <a style="cursor: pointer;"><i class="fa fa-fw fa-id-card-alt"></i> <span>Contatos</span></a>
                                    <ul class="list-unstyled">
                                        <li><a href="/contato" id="contato"><i class="far fa-id-card"></i> Lista Contatos</a></li>
                                    </ul>
                            </li>
                        <?}?>                     
                        
                        <? if($log == "1") {?>
                            <li class="submenu">
                                <a style="cursor: pointer;"><i class="fa fa-fw fa-user"></i> <span>Usuários</span></a>
                                    <ul class="list-unstyled">
                                        <li><a href="/newuser" id="newuser"><i class="fas fa-plus-circle"></i> Novo Usuário</a></li>
                                        <li><a href="/usuarios" id="newuser"><i class="fas fa-users"></i> Todos os usuários</a></li>
                                    </ul>
                            </li>
                        <?}?>

                        <? if($log == "1" or $log == "2") {?>
                            <li class="submenu">
                                <a style="cursor: pointer;"><i class="fas fa-code"></i> <span>Configurações Site</span></a>
                                    <ul class="list-unstyled">
                                        <li><a href="/newslider" id="newuser"><i class="far fa-plus-square"></i> Novo slider</a></li>
                                        <li><a href="/sliderslist" id="newuser"><i class="far fa-newspaper"></i> Todos os sliders</a></li>
                                    </ul>
                            </li>
                        <?}?>
                                            
                        <!-- <li class="submenu">
                            <a href="#"><i class="fa fa-fw fa-tv"></i> <span> User Interface </span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled">
                                    <li><a href="ui-alerts.html">Alerts</a></li>
                                    <li><a href="ui-buttons.html">Buttons</a></li>
                                    <li><a href="ui-cards.html">Cards</a></li>
                                    <li><a href="ui-carousel.html">Carousel</a></li>
                                    <li><a href="ui-collapse.html">Collapse</a></li>
                                    <li><a href="ui-icons.html">Icons</a></li>
                                    <li><a href="ui-modals.html">Modals</a></li>
                                    <li><a href="ui-tooltips.html">Tooltips and Popovers</a></li>
                                </ul>
                        </li> -->
    
                        <!-- <li class="submenu">
                            <a href="#"><i class="fa fa-fw fa-file-text-o"></i> <span> Forms </span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled">
                                    <li><a href="forms-general.html">General Elements</a></li>
                                    <li><a href="forms-select2.html">Select2</a></li>
                                    <li><a href="forms-validation.html">Form Validation</a></li>
                                    <li><a href="forms-text-editor.html">Text Editors</a></li>
                                    <li><a href="forms-upload.html">Multiple File Upload</a></li>
                                    <li><a href="forms-datetime-picker.html">Date and Time Picker</a></li>
                                    <li><a href="forms-color-picker.html">Color Picker</a></li>
                                </ul>
                        </li>
                         -->
                        <!-- <li class="submenu">
                            <a href="#"><i class="fa fa-fw fa-th"></i> <span> Plugins </span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled">
                                    <li><a href="star-rating.html">Star Rating</a></li>
                                    <li><a href="range-sliders.html">Range Sliders</a></li>
                                    <li><a href="tree-view.html">Tree View</a></li>
                                    <li><a href="sweetalert.html">SweetAlert</a></li>
                                    <li><a href="calendar.html">Calendar</a></li>
                                    <li><a href="gmaps.html">GMaps</a></li>
                                    <li><a href="counter-up.html">Counter-Up</a></li>
                                </ul>
                        </li> -->
    
                        <!-- <li class="submenu">
                            <a href="#"><i class="fa fa-fw fa-image"></i> <span> Images and Galleries </span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled">
                                    <li><a href="media-fancybox.html"><span class="label radius-circle bg-danger float-right">cool</span> Fancybox </a></li>								
                                    <li><a href="media-masonry.html">Masonry</a></li>
                                    <li><a href="media-lightbox.html">Lightbox</a></li>
                                    <li><a href="media-owl-carousel.html">Owl Carousel</a></li>
                                    <li><a href="media-image-magnifier.html">Image Magnifier</a></li>
                                    
                                </ul>
                        </li> -->
                        
                        <!-- <li class="submenu">
                            <a href="#"><span class="label radius-circle bg-danger float-right">20</span><i class="fa fa-fw fa-copy"></i><span>Example</span></a>
                                <ul class="list-unstyled">								
                                    <li><a href="page-pricing-tables.html">Pricing Tables</a></li>
                                    <li><a target="_blank" href="page-coming-soon.html">Countdown</a></li>								
                                    <li><a href="page-invoice.html">Invoice</a></li>                        
                                    <li><a href="page-login.html">Login / Register</a></li>								
                                    <li><a href="page-blank.html">Blank Page</a></li>
                                </ul>
                        </li> -->
    
                        <!-- <li class="submenu">
                            <a href="#"><span class="label radius-circle bg-primary float-right">9</span><i class="fa fa-fw fa-indent"></i><span> Menu Levels </span></a>
                                <ul>
                                    <li>
                                        <a href="#"><span>Second Level</span></a>
                                    </li>
                                    <li class="submenu">
                                        <a href="#"><span>Third Level</span> <span class="menu-arrow"></span> </a>
                                            <ul style="">
                                                <li><a href="#"><span>Third Level Item</span></a></li>
                                                <li><a href="#"><span>Third Level Item</span></a></li>
                                            </ul>
                                    </li>                                
                                </ul>
                        </li> -->

                        <!-- <li class="submenu">
                            <a class="pro" href="#"><i class="fa fa-fw fa-star"></i><span>t </span><span class="menu-arrow"></span></a>
                                <ul class="list-unstyled">								
                                    <li><a target="_blank" href="#">item</a></li>
                                </ul>
                        </li>  -->
                        
                </ul>
    
                <div class="clearfix"></div>
    
                </div>
            
                <div class="clearfix"></div>
    
            </div>
    
        </div>
        <!-- End Sidebar -->
    
    
        <div class="content-page">
        
            <!-- Start content -->
            <div class="content">
                
                <div class="container-fluid">                      

                    <div class="mt-5">
                        <?= $this->content();?>
                    </div>

                </div>
                <!-- END container-fluid -->    
            </div>
            <!-- END content -->    
        </div>
        <!-- END content-page -->

        
        <footer class="footer">
            <span class="text-right">
                <a target="_blank" href="http://www.dnsecury.com">DNSecury</a>
            </span>
            <span class="float-right">
            Powered by <a target="_blank" href="http://www.dnsecury.com"><b>A DNSecury</b></a>
            </span>
        </footer>    
    </div>
    <!-- END main -->

    <script src="./assets/js/js-panel/modernizr.min.js"></script>
    <script src="./assets/js/js-panel/jquery.min.js"></script>
    <script src="./assets/js/js-panel/detect.js"></script>
    <script src="./assets/js/js-panel/fastclick.js"></script>
    <script src="./assets/js/js-panel/jquery.blockUI.js"></script>
    <script src="./assets/js/js-panel/jquery.nicescroll.js"></script>        
    <script src="./assets/js/js-panel/moment.min.js"></script>


    <!-- App js -->
    <script src="./assets/js/js-panel/pikeadmin.js"></script>

    <!-- BEGIN Java Script for this page -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    
	<!-- Counter-Up-->
	<script src="./assets/js/js-panel/jquery.waypoints.min.js"></script>
	<script src="./assets/js/js-panel/jquery.counterup.min.js"></script>
    <!-- END Java Script for this page -->    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <script src="./assets/js/main.js"></script>
    </body>
    
</html>
