<section id="home" class="d-flex box-one box-one-index"> <!-- Capa -->

    <video autoplay muted loop class="bg_video_index">
    <source src="vdo/Electronics.mp4" type="video/mp4">
    </video>

<div class="container align-self-center">

    <div class="row">
        <div class="col-md-12 capa">

        <h2>DNSecury - desenvolvimento e soluções em segurança cibernética</h2>
        <a href="/servicos" class="btn btn-custom btn-lg btn-success">
            Serviços
        </a>

        </div>
    </div>

    </div>
</section><!-- Fim capa -->

<!--<section class="bg-info conteudo-0">
    <div class="container">
    <div class="row">
        <div class="col-md-10">Contrate um de nossos agentes para aperfeiçoar a segurança da sua empresa </div>
    </div>
    </div>
</section> -->


<section id="conteudo-1" class=""><!-- Conteúdo 1 -->

    <div class="container separador">
    <div class="row">

        <div class="col-md-4 conteudo_custom">
        <img src="imagens/infra.jpg" class="img-custom img-custom-p1 d-none d-md-block border_cus" href="#">
        </div>
        <div class="col-md-8 conteudo_custom">

        <h4>Teste de penetração avançado</h4>
        <div>
            <h6>O mais pedido por grandes corporações</h6>
            <div>
            <p>Lorem Ipsum é simplesmente texto fictício da indústria tipográfica e de impressão. O Lorem Ipsum tem sido o texto fictício padrão da indústria desde os anos 1500, quando uma impressora desconhecida pegou uma galé do tipo e subiu para fazer um livro de espécimes de tipo.</p>
            </div>
        </div>

        <p><a href="#">Ver mais...</a></p>

        </div>

    </div>

    </div>

    <div class="container separador">
    <div class="row">

        <div class="col-md-4 conteudo_custom">
        <img src="imagens/web_security.jpg" class="img-custom img-custom-p1 d-none d-md-block border_cus" href="#">
        </div>
        <div class="col-md-8 conteudo_custom">

        <h4>Teste de penetração em aplicações web</h4>
        <div>
            <h6>O mais pedido por grandes e pequenas empresas</h6>
            <div>
            <p align="﻿justify">Lorem Ipsum é simplesmente texto fictício da indústria tipográfica e de impressão. O Lorem Ipsum tem sido o texto fictício padrão da indústria desde os anos 1500, quando uma impressora desconhecida pegou uma galé do tipo e subiu para fazer um livro de espécimes de tipo.</p>
            </div>
        </div>

        <p><a href="#">Ver mais...</a></p>

        </div>

    </div>

    </div>

</section><!-- Fim conteúdo 1 -->

<br>


<section class="bg-info conteudo-0">
    <div class="container">
    <div class="row">
        <div class="col-md-10">Avanços tecnológicos</div>
    </div>
    </div>
</section>

<section id="conteudo-2" class=""><!-- Conteúdo 2 -->

    <div class="container separador">
    <div class="row">

        <div class="col-md-4 conteudo_custom pt-2">
        <img src="imagens/imagem-1.jpg" class="img-custom img-custom-p2 border_cus">
        <div>

            <h5>Avanço Tecnológico</h5>
            <p>Lorem Ipsum é simplesmente texto fictício da indústria tipográfica e de impressão. O Lorem Ipsum tem sido o texto fictício padrão da indústria desde os anos 1500, quando uma impressora desconhecida pegou uma galé do tipo e subiu para fazer um livro de espécimes de tipo.</p>
            <p><a href="#">Ver mais</a></p>

        </div>
        </div>

        <div class="col-md-4 conteudo_custom pt-2">
        <img src="imagens/architecture.jpg" class="img-custom img-custom-p2 border_cus">
        <div>

            <h5>Mercado de Trabalho</h5>
            <p>Lorem Ipsum é simplesmente texto fictício da indústria tipográfica e de impressão. O Lorem Ipsum tem sido o texto fictício padrão da indústria desde os anos 1500, quando uma impressora desconhecida pegou uma galé do tipo e subiu para fazer um livro de espécimes de tipo.</p>
            <p><a href="#">Ver mais</a></p>

        </div>
        </div>

        <div class="col-md-4 conteudo_custom pt-2">
        <img src="imagens/network.jpg" class="img-custom img-custom-p2 border_cus">
        <div>

            <h5>DNSecury</h5>
            <p>Lorem Ipsum é simplesmente texto fictício da indústria tipográfica e de impressão. O Lorem Ipsum tem sido o texto fictício padrão da indústria desde os anos 1500, quando uma impressora desconhecida pegou uma galé do tipo e subiu para fazer um livro de espécimes de tipo.</p>
            <p><a href="#">Ver mais</a></p>

        </div>
        </div>

    </div>

    </div>

</section><!-- Fim conteúdo 2 -->


<section class="box-conteudo-2">.</section>

<section class="bg-info conteudo-0"><!-- Inicio faixa 3 -->
    <div class="container">
    <div class="row">
        <div class="col-md-10 futuro-sec">O futuro está mudando é você deve se aperfeiçoar</div>
    </div>
    </div>
</section><!-- Fim faixa 3 -->


<section id="conteudo-3"><!-- Inicio conteúdo 3 -->

    <div class="container">
    <div class="row">

        <div class="col-md-2 d-none d-lg-block ">
        <span><img class="" width="130" src="imagens/graduation-cap.png"></span>
        </div>

        <div class="col-md-10">
        <div class="text-white pt-3">

            <h3>Torne-se um profissional na área de Tecnologia da Informação.</h3>
            <div>
            <p>Lorem Ipsum é simplesmente texto fictício da indústria tipográfica e de impressão.</p>
            </div>

        </div>
        </div>

    </div>
    </div>

</section><!-- Fim conteúdo 3 -->



<!-- Inicio apresentação dos cursos -->
<section class="box-conteudo-3" style="background: rgba(0, 0, 0, 0.7);">
    <div class="container">

        <div class="text-white">

            <!-- Inicio row 1 -->
            <div id="owl-slider" class="owl-carousel pt-4">

            <?php foreach($this->view->elements_slider as $key => $value) {?>
                <div class="item">
                    <div class="border mt-1 item-slider" style="background: rgba(0, 0, 0, 0.7);">
                        <a href="<?= $value['link_element'] ?>" target="__blank">
                            <h4><?= $value['title_element']?></h4>
                            <div class="">
                                <img src="./imagens/slider/<?= $value['name_file'] ?>" class="img-slider" alt="">
                            </div>
                            <div class="desc-slider">
                                <p><?= $value['desc_element'] ?></p>
                            </div>
                        </a>
                    </div>
                </div>
            <?}?>

            </div>
            <!-- Fim row 1 -->

        </div>

    </div>
</section> 
<!-- Fim apresentação dos cursos -->
