<section id="home" class="d-flex box-one border-bottom bg_quem_somos"> <!-- Capa -->

      <div class="container align-self-center">

        <div class="row">
          <div class="col-md-12 capa">

            <h2 style="color: rgba(red, rgba(178, 233, 233, 0.26), blue, alpha);">Segurança em primeiro lugar é essencial para a disponibilidade dos negócios</h2>

          </div>
        </div>

      </div>
    </section><!-- Fim capa -->


    <section id="servicosPage">

</section>