<section id="home" class="d-flex box-one box-one-servicos border-bottom"> <!-- Capa -->

    <video autoplay muted loop class="bg_video_services">
    <source src="vdo/Security.mp4" type="video/mp4">
    </video>

    <div class="container align-self-center">

    <div class="row">
        <div class="col-md-12 capa">

        <h2 class="text-white">Segurança em primeiro lugar é essencial para a disponibilidade dos negócios</h2>

        </div>
    </div>

    </div>
</section><!-- Fim capa -->


<section id="servicosPage">
</section>
